version: '3.8'

services:
  api:
    image: ep-mern-ms-ticketservice:latest
    container_name: ep-mern-ms-ticketservice
    # stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./microservice
    volumes:
      - /api/node_modules
      - ./api:/app
    ports:
      - "4001:4001"
    # networks: 
    #   - ep-mern